### ISSUE TITLE
[To-do list]개발 4일차 2021-04-01

### ISSUE THREAD

**Issue by naro-Kim** [HICC-Introduction/B652009-Todo_list#10]
**! 오늘 한 일**

- 하루종일 기능 구현을 위해 js를 공부했지만 겉핥기식으로 공부해서 그런지 event와 method 사용과 function 정의가 미숙하다
- 클래스와 오브젝트를 어떻게 섞어서 함수를 만들어보려 하는데 자꾸만 오류가 생긴다
- [x]  너무 답답해서 CSS를 먼저 기본만 정리했다. 
![image](https://user-images.githubusercontent.com/51940808/113312816-a0848d00-9345-11eb-9c4d-b8a442ecd3d7.png)

**! 개발 4일차, 진행이 더디다**

분명 문법은 아는데 로직을 짜는 것과 아는 것은 다른 듯 하다.
가장 큰 문제는 function안에서 createElement 메소드로 만들어낸 class에 다시 css를 입히려면 어떻게 해야하는가?
todoDiv.appendChild(newTodo)로 버튼 + 텍스트 + 라벨로 구성된  투두 항목을 새로 만든 다음, 그 안의 버튼이 체크되면 텍스트의 Css가 변해야한다...

**! 남은 일**

남은 시간 동안 할 수 있을 진 모르겠지만, 할 수 있는 데 까진 해야지.. 위에부터 구현 가능성이 높은 순
- [ ] 미디어쿼리로 width 최솟값 지정 
- [x] Category값 받아서 todo 라벨 설정하기
- [ ] Edit / Delete 버튼을 클릭하면 글씨 색과 내용이 바뀌게 하기
- [x] Checkbox를 누르면 Input value의 text decoration : line through로 변하게 만들기
- [ ] tab 전환

**Reference**
- JS web docs
https://developer.mozilla.org/ko/docs/Web/API/Event

- 오류를 익히기 위해 참고한 블로그
https://blog.meeta.io/10
https://developer.mozilla.org/ko/docs/Web/API/Event
https://m.blog.naver.com/PostView.nhn?blogId=neo_start&logNo=220311156809&proxyReferer=https:%2F%2Fwww.google.com%2F

- CSS 참고용 블로그
- Input과 Button을 겹치기
https://m.blog.naver.com/PostView.nhn?blogId=rwans0397&logNo=220696890907&proxyReferer=https:%2F%2Fwww.google.com%2F
