### ISSUE TITLE
[To-do list]개발 5일차 2021-04-02

### ISSUE THREAD

**Issue by naro-Kim** [HICC-Introduction/B652009-Todo_list#11]
**오늘 한 일**
---
- [x] Priority와 Category를 선택하지 않았을 때 alert이 등장하도록 기능 구현
- [x] 선택한 Category가 Todo Label로 들어가는 기능 구현
- [x] Checkbox 클릭 시 line through로 변경하는 기능 구현
- [ ] (진행중) 작성한 todo의 Edit모드와 Delete모드 구현

-> Edit mode and Delete mode. input.donechk {appearance:none;}으로 만들거나 removeChild(doneBtn)를 사용해 checkbox를 리스트에서 지워준다. 대신 그 자리에 edit acitvation icon을 넣어준다. 

**현재 진행중인 로컬 파일**
---
![image](https://user-images.githubusercontent.com/51940808/113424613-6aa9dc00-940b-11eb-8b0d-b7eca7844f55.png)

**4/3 내일 할 일**
---
- [ ] 탭 전환 기능 구현
- [ ] CSS 다듬기

**Reference**
---
https://jqueryui.com/
