### ISSUE TITLE
[To-do list]설계 3일차 2021-03-27

### ISSUE THREAD

**Issue by naro-Kim** [HICC-Introduction/B652009-Todo_list#2]
2일차는 컨디션 상 문제로 건너뛰고, 3일차로 진행합니다.
---
- [x] 화면 설계서 웹앱형으로 수정
- [x] JS todo tutorial 강의 수강 완료
- [x] 대략적인 JS function 목록 조사 및 정리..
     - addCheck, deleteCheck, filterPriority, filterCategory, 

---
Next
3/28
- [x] 기능 명세서 작성 완료
- [x] 화면 설계서 모든 페이지 디자인 완료
- [x] 화면 흐름도 작성

----
내일 기능 명세서와 함께 자세한 화면 설계서를 올릴 예정입니다.
![image](https://user-images.githubusercontent.com/51940808/112723389-8c115080-8f51-11eb-9ca1-26163d11b1ef.png)
위는 진행중인 화면 설계서로, 와이어프레임 상태입니다.

**Comment by Lai-khan** [comment]
PC랑 모바일 두 버전으로 만들 생각이신가요?
아니면 반응형으로 해서 하나로 만들 생각이신가요?

**Comment by naro-Kim** [comment]
반응형으로 하나로 만들고 싶은데, 버튼의 위치나 아이콘의 위치가 생각처럼 이동할 지 모르겠어서
두 가지로 만들 수도 있을 것 같습니다! 오늘 내로 화면 설계서, 흐름도 같이 올리면서 이야기 나누면 좋겠습니당
