### ISSUE TITLE
[To-do list]설계 4일차 2021-03-28

### ISSUE THREAD

**Issue by naro-Kim** [HICC-Introduction/B652009-Todo_list#5]
### 설계 부분

- [x] 기능 명세서 작성 완료
- [x] 화면 설계서 모든 페이지 디자인 완료
- [x] 화면 흐름도 작성

[기능 명세서](https://github.com/HICC-Introduction/B652009-Todo_list/issues/3#issue-842730389)
[화면 설계서](https://github.com/HICC-Introduction/B652009-Todo_list/issues/4#issue-842737681)
[화면 흐름도](https://github.com/HICC-Introduction/B652009-Todo_list/issues/6#issue-842746904)

### Javascript 튜토리얼 공부중..
아래 링크의 영상들을 보고 Javascript to-do 기능 구현에 필요한 문법과 코드를 공부하는 중입니다..

https://nomadcoders.co/javascript-for-beginners/
https://youtu.be/Ttf3CEsEwMQ

### 설계까지의 후기
- 구현을 고려해서 내가 개발할 수 있다는 조건을 두고 화면 설계를 해보니 생각보다 JS 학습 깊이가 깊지 않았던 것을 깨달았다.
- 과연 내가 그린 모든 기능과 화면을 구현할 수 있을지 두렵긴 한데 시간을 많이 투자해야할 듯 하다.
- 기능 구현 JS가 먼저일까, CSS가 먼저일까? 일단 앞으로 js에 시간을 많이 쏟고 Figma의 inspector를 이용해 css를 빠르게 커버해보려 한다.

**Comment by Lai-khan** [comment]
CSS와 JS 둘 중에 하나를 고르라면 우선 JS일 것 같습니다. Todo list에서 새로운 할일을 추가, 수정, 삭제하는 부분의 로직에 JS가 필수이기 때문입니다.

CSS는 구상하신 화면의 디자인이 너무 고퀄리티라 잘 구현하실 수 있을까 조금 걱정되지만 기존에 CSS 강의를 들으셨다고 하니 우선 JS에 더 시간을 쏟는 것이 좋을 것 같습니다.
