### ISSUE TITLE
[To-do list]개발 3일차 2021-03-31

### ISSUE THREAD

**Issue by naro-Kim** [HICC-Introduction/B652009-Todo_list#9]
앞서 29일날 계획한 바는 다음과 같았다.

**3/30**
- [x] 날린만큼 다시 코드 짜기
- [x] Input 추가 기능 구현
    - input을 클릭하면, todo-list의 하위에 class가 todo인 div를 만든다.
    - 이 div의 하위에 todo의 상태 체크를 위한 class가 done_chk인 input button을 만든다.
    - input에서 입력했던 내용이 들어갈 class가 todo-item인 li를 만든다.
    - 마지막으로, 인풋을 입력하기에 앞서 선택했던 category 속성을 받아 표시해줄 라벨을 만든다.

**3/31**

- [ ] Edit 기능 구현
- [x] Filter CSS
- 위 두가지를 작성하기 전, 구상했던 화면에 맞게 Input의 카테고리 설정값을 받아 라벨을 만드는 법또한 넣고자 한다.
- 다만 해당 기능들을 구현하기 위해 튜토리얼을 따라가던 중, 개념과 복잡한 구조때문에 이해가지 않는 부분과 함께 응용을 위해서 JS 개념 공부를 보충하고 있다.
-특히, 해당 링크처럼 Input을 완료했을 때 text decoration이 바뀌는 부분도 구현해야한다. https://stackoverflow.com/questions/47618503/change-style-of-label-when-checkbox-gets-checked-ionic-3

**Reference**
- adding Elements
https://en.wikibooks.org/wiki/JavaScript

- createElement()
https://developer.mozilla.org/en-US/docs/Web/API/Document/createElement
https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements

- var, let, const 변수
https://gist.github.com/LeoHeo/7c2a2a6dbcf80becaaa1e61e90091e5d
